"""
Data models for the LLM voting experiment.
"""
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from enum import Enum
from datetime import datetime


class TestType(Enum):
    """The four test conditions."""
    CONTEXT_ON_NO_SELF_VOTE = "test_1"  # Context ON + No Self-Vote
    CONTEXT_ON_SELF_VOTE = "test_2"     # Context ON + Self-Vote Allowed
    CONTEXT_OFF_ANONYMOUS_SELF_VOTE = "test_3"  # Context OFF + Anonymous + Self-Vote
    CONTEXT_OFF_ANONYMOUS_NO_SELF_VOTE = "test_4"  # Context OFF + Anonymous + No Self-Vote


@dataclass
class Answer:
    """Represents an answer generated by an LLM."""
    model_name: str
    prompt: str
    text: str
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Vote:
    """Represents a vote cast by an LLM."""
    voter_model: str
    voted_for_model: str  # The model whose answer was voted for
    voted_for_index: int  # Index of the answer in the shuffled list (for anonymous tests)
    test_type: TestType
    reasoning: Optional[str] = None
    is_self_vote: bool = False
    is_violation: bool = False  # Did they violate instructions (e.g., self-vote when not allowed)
    recognized_own_style: Optional[bool] = None  # For Test 4: did they recognize their own answer?
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ExperimentRun:
    """Represents a single experiment run for one prompt."""
    prompt: str
    test_type: TestType
    answers: List[Answer]  # All answers generated for this prompt
    votes: List[Vote]  # All votes cast in this test
    answer_mapping: Dict[int, str] = field(default_factory=dict)  # For anonymous tests: index -> model_name
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ExperimentResults:
    """Aggregated results from all experiment runs."""
    runs: List[ExperimentRun]
    metrics: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.now)

